dkml-workflows: upgrade to prerelease

diff --git a/ci/setup-dkml/gh-linux/pre/action.yml b/ci/setup-dkml/gh-linux/pre/action.yml
--- a/ci/setup-dkml/gh-linux/pre/action.yml
+++ b/ci/setup-dkml/gh-linux/pre/action.yml
@@ -330,6 +330,10 @@ runs:
 
         # dkml-runtime-distribution
 
+        #   For 'Diagnose Visual Studio environment variables (Windows)' we need dkml-runtime-distribution
+        #   so that 'Import-Module Machine' and 'Get-VSSetupInstance' can be run.
+        #   The version doesn't matter too much, as long as it has a functioning Get-VSSetupInstance.
+        #   commit 1a3ec82dd851751a95e6a4797387a8163c51520e = tag v0.4.0-prerel20
         case "$dkml_host_abi" in
         windows_*)
             section_begin checkout-dkml-runtime-distribution 'Checkout dkml-runtime-distribution'
@@ -347,7 +351,7 @@ runs:
         # Constants
         SHA512_DEVNULL='cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e'
         #   Edited by https://gitlab.com/diskuv/diskuv-ocaml/contributors/release.sh
-        DEFAULT_DISKUV_OPAM_REPOSITORY_TAG=cc9518fa5630bfbe24d4c5e0e2cc29af513037ce
+        DEFAULT_DISKUV_OPAM_REPOSITORY_TAG=26dfc8a980d30023a05c73e6bd38425ae34488d5
         # Constants
         #   Should be edited by release.sh, but ...
         #   Can't be 1.0.0 or later until https://github.com/ocaml/opam-repository/pull/21704 ocaml-option-32bit
@@ -1390,9 +1394,11 @@ runs:
             windows_*)
                 if ! grep -q '\(^|\[\)DiskuvOCamlMSYS2Dir ' ".ci/sd4/setenv.$do_setenv_SWITCH.txt"; then
                     if [ -x /usr/bin/cygpath ]; then
-                        MSYS2_DIR_NATIVE=$(/usr/bin/cygpath -aw "msys64")
+                        MSYS2_DIR_NATIVE=$(/usr/bin/cygpath -aw /)
                     else
-                        MSYS2_DIR_NATIVE="$PWD"
+                        # If we are already inside MSYS2 then MSYSTEM_PREFIX should be set. But cygpath should be there as well!!
+                        echo "FATAL: Could not locate MSYS2: there was no cygpath" >&2
+                        exit 3
                     fi
                     MSYS2_DIR_NATIVE_ESCAPED=$(printf "%s" "$MSYS2_DIR_NATIVE" | sed 's/\\/\\\\/g')
                     opamrun option --switch "$do_setenv_SWITCH" setenv+="DiskuvOCamlMSYS2Dir = \"$MSYS2_DIR_NATIVE_ESCAPED\""
@@ -1564,7 +1570,7 @@ runs:
       shell: bash
       run: |
         set -x
-        echo '54ccd7-${{ inputs.FDOPEN_OPAMEXE_BOOTSTRAP }}-${{ steps.full_matrix_vars.outputs.dkml_host_abi }}-${{ steps.full_matrix_vars.outputs.opam_abi }}-${{ steps.full_matrix_vars.outputs.bootstrap_opam_version }}' > .ci/sd4/cachekey.opam.binaries
+        echo 'eeff28-${{ inputs.FDOPEN_OPAMEXE_BOOTSTRAP }}-${{ steps.full_matrix_vars.outputs.dkml_host_abi }}-${{ steps.full_matrix_vars.outputs.opam_abi }}-${{ steps.full_matrix_vars.outputs.bootstrap_opam_version }}' > .ci/sd4/cachekey.opam.binaries
         echo '${{ steps.full_matrix_vars.outputs.abi_pattern }}-${{ steps.full_matrix_vars.outputs.vsstudio_arch }}-${{ steps.full_matrix_vars.outputs.vsstudio_hostarch }}-${{ steps.full_matrix_vars.outputs.vsstudio_dir }}-${{ steps.full_matrix_vars.outputs.vsstudio_vcvarsver }}-${{ steps.full_matrix_vars.outputs.vsstudio_winsdkver }}-${{ steps.full_matrix_vars.outputs.vsstudio_msvspreference }}-${{ steps.full_matrix_vars.outputs.vsstudio_cmakegenerator }}' > .ci/sd4/cachekey.vsstudio
         echo '${{ inputs.OCAML_COMPILER }}-${{ inputs.DISKUV_OPAM_REPOSITORY }}-${{ inputs.DKML_COMPILER }}-${{ inputs.CONF_DKML_CROSS_TOOLCHAIN }}' > .ci/sd4/cachekey.ci.inputs
 
@@ -1672,14 +1678,14 @@ runs:
         PIN_DIGESTIF: '1.0.1'
         PIN_DUNE: '2.9.3+shim.1.0.2~r0'
         PIN_DUNE_CONFIGURATOR: '2.9.3'
-        PIN_DKML_APPS: '1.0.1'
+        PIN_DKML_APPS: '1.0.2~prerel8'
         PIN_OCAMLBUILD: '0.14.0'
         PIN_OCAMLFIND: '1.9.1'
         PIN_OCP_INDENT: '1.8.2-windowssupport'
         PIN_PPX_EXPECT: 'v0.14.1'
         PIN_PTIME: '0.8.6-msvcsupport'
         PIN_TIME_NOW: 'v0.14.0'
-        PIN_WITH_DKML: '1.0.1'
+        PIN_WITH_DKML: '1.0.2~prerel8'
       run: |
         sh .ci/sd4/run-setup-dkml.sh GITHUB_WORKSPACE "$GITHUB_WORKSPACE"
 
